### ISSUE TITLE
Not working due to TypeError exception.

### ISSUE THREAD

**Issue by etoundi1er** [alvesjtiago/hover-locales#3]
The package currently breaks due to a NoneType being provided instead of a string.
I have prepared a pull request which fixes that issue ad now it works

```python
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 462, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 701, in <lambda>
    run_callback('on_hover', callback, lambda: callback.on_hover(v, point, hover_zone))
  File "/Users/franketoundi/Library/Application Support/Sublime Text 3/Packages/hover-locales/hover_locales.py", line 138, in on_hover
    html += '<span style="color: #f00;">' + key + "</span>" + ": " + value["string"]
TypeError: Can't convert 'NoneType' object to str implicitly
```

**Comment by alvesjtiago** [comment]
Thanks for opening the issue and the PR @etoundi1er, truly appreciate it. I will review it today and merge as soon as possible.
